language: python

sudo: false

matrix:
  include:
    - python: 3.8
      env: DJANGO='dj32'
    - python: 3.9
      env: DJANGO='dj32'
    - python: 3.10
      env: DJANGO='dj32'
    - python: 3.8
      env: DJANGO='dj40'
    - python: 3.9
      env: DJANGO='dj40'
    - python: 3.10
      env: DJANGO='dj40'

install:
  - pip install tox coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then export PY_VER=py39; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.10' ]]; then export PY_VER=py310; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
